language: node_js

cache:
  directories:
  - node_modules

git:
  depth: 3

node_js:
- 6.9.4

install:
- cd deployment.script && npm install

before_script:
- cd deployment.script && npm run build

script:
- cd deployment.script && npm run deploy
