language: node_js

cache:
  directories:
  - node_modules

git:
  depth: 3

node_js:
- 6.9.4

install:
- npm install

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
- npm run build.deploy.script

script:
- npm run deploy
