language: node_js

cache:
  directories:
  - node_modules

git:
  depth: 3

node_js:
- 6.9.4

script:
- cd deployment.script && npm install
- cd deployment.script && npm run build
- cd deployment.script && npm run deploy
