tag: lumen
history:
    adhocBranchName: __adhoc--lumen--current--local--2018-07-05--2.18pm
    commitMessage: __adhoc--lumen--current--local--2018-07-05--2.18pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bd109d77b83acd83c207e7e45cf1c43c61b6412f
            message: >-
                JS dist files --
                __adhoc--lumen--current--local--2018-07-05--2.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/684621cfa959990ebb5e097eff317048b130cca8
            message: >-
                Localized strings --
                __adhoc--lumen--current--local--2018-07-05--2.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/802c33d07437a7dc1bf329d46be17ade3aa113f2
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a67a8a883a6df6fa5a167796d09a37cf8f402829
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/35109fd71797d3bd1608987ce7a420080a93051f
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--lumen--current--local--2018-07-05--2.18pm
