tag: adhoc
history:
    adhocBranchName: __adhoc--current--local--2018-02-07--2.32pm--insights-sso-pivotbridge
    commitMessage: __adhoc--current--local--2018-02-07--2.32pm--insights-sso-pivotbridge
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2f87740ed8b7e532c43019b1279c9a0e88ccfdfb
            message: >-
                JS dist files --
                __adhoc--current--local--2018-02-07--2.32pm--insights-sso-pivotbridge
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a01dd0ba871b6b0a30ad227a4373ecdb5b573316
            message: >-
                Localized strings --
                __adhoc--current--local--2018-02-07--2.32pm--insights-sso-pivotbridge
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3cff29721387767a36dd2776be586b0655419c00
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9bfed396c3161135509785755d01b1537a001cc8
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c2af81c3f5120866c20c95c87c6bbe188f3b6261
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--current--local--2018-02-07--2.32pm--insights-sso-pivotbridge
