version: 1.1.3-adhoc.5
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.3-adhoc.5
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.3-adhoc.5
deployedAt: 2018-01-19 3:38 am UTC  (2018-01-18 7:38 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--16.0.8918.5450--2018-01-18--7.35pm
    commitMessage: __adhoc--beta--16.0.8918.5450--2018-01-18--7.35pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/26c67d66faee462c67771649048f5f08534512f7
            message: >-
                JS dist files --
                __adhoc--beta--16.0.8918.5450--2018-01-18--7.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/028f6e7ee7d869dd7b6361fe4fa07f4c9544b11b
            message: >-
                Localized strings --
                __adhoc--beta--16.0.8918.5450--2018-01-18--7.35pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7c79e7eb0df9cc6b6805ec3a32a8f5af92038c02
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/be0b72d78ea6db775760b40732c661b1e973c7b5
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ea0de320950f840539f2eeb895d389ecb307791d
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--16.0.8918.5450--2018-01-18--7.35pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.3-adhoc.5/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.3-adhoc.5/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/330654571