version: 1.1.9-operational.1
tag: operational
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-operational.1
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-operational.1
deployedAt: 2018-05-12 4:24 am UTC  (2018-05-11 9:24 pm Pacific Time)

history:
    adhocBranchName: __adhoc--operational--current--local--2018-05-11--9.21pm
    commitMessage: __adhoc--operational--current--local--2018-05-11--9.21pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a28f8df74d1c78053827e0a83d7dd89333a9b2e8
            message: >-
                JS dist files --
                __adhoc--operational--current--local--2018-05-11--9.21pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/287c62e46762462d59ecd92ce26889e211452177
            message: >-
                Localized strings --
                __adhoc--operational--current--local--2018-05-11--9.21pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/84bba955a469acfc89e21b1e3acf8382c7317043
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f6f4cb854e1c563163d50414ecd547bf2d562c1d
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9edd82af9117585af9e6e5070f1eca20184e32de
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--operational--current--local--2018-05-11--9.21pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-operational.1/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-operational.1/dist/office.d.ts
    builds using this same tag ("operational"):
        https://unpkg.com/@microsoft/office-js@operational/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/378003019