version: 1.1.5-experiment-daedalus.1
tag: experiment-daedalus
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-experiment-daedalus.1
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-experiment-daedalus.1
deployedAt: 2018-01-25 9:43 pm UTC  (2018-01-25 1:43 pm Pacific Time)

history:
    adhocBranchName: __adhoc--experiment-daedalus--release--local--2018-01-25--1.39pm
    commitMessage: Updated typings to have batch function type
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/55d50397f4d42daa054296c2693b096d62372e77
            message: JS dist files -- Updated typings to have batch function type
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b15fc7117ca8ace2af7c0ffcf75a9d4f56f76785
            message: Localized strings -- Updated typings to have batch function type
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3a2a364838023a134d2b119d22583b7ac43330ae
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e54456b7eef61a43f9360d6b2ddfecfd913e2af8
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fb5c029fee219aae4b4d2ea05ace93d7aee37f52
            message: >-
                [BEGIN PUBLISH UPDATES] -- Updated typings to have batch
                function type


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-experiment-daedalus.1/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-experiment-daedalus.1/dist/office.d.ts
    builds using this same tag ("experiment-daedalus"):
        https://unpkg.com/@microsoft/office-js@experiment-daedalus/dist/office.js
        https://unpkg.com/@microsoft/office-js@experiment-daedalus/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/333473622