tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-03-23--5.12pm
    commitMessage: Manually-tweaked PPT files
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/81fd4bd8359019006a008bbc1107d45014376741
            message: JS dist files -- Manually-tweaked PPT files
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/305b9aa4b1f47b5ebedafe80972fb0a45dff0f76
            message: Localized strings -- Manually-tweaked PPT files
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/547dfab149b09c03b8d73cde17824a561898c59f
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/daf6a544a50d6801b47907e4958ddf033f7f2064
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0ac0e14f88a13ae79e9c3c04e6537a76861578d9
            message: '[BEGIN PUBLISH UPDATES] -- Manually-tweaked PPT files'
