tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-01-17--8.46pm--sso
    commitMessage: word and excel sso
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1e7888c256921eef6d54be26713d39f0a15b3f99
            message: JS dist files -- word and excel sso
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/eb458c7eb6a1caa1ebcdc871a1e2eed9145d01e9
            message: Localized strings -- word and excel sso
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/98ea7d8ac0745ce9612bfbea056b1142cce60309
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/eb1ca727e9cf2aec5517e96aeea9b71620e0f65a
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3b0b2f253fd6c0414b177e18f449a104a79225c7
            message: '[BEGIN PUBLISH UPDATES] -- word and excel sso'
