tag: experiment-kiwi
history:
    adhocBranchName: __adhoc--experiment-kiwi--release--local--2018-02-08--8.18pm
    commitMessage: __adhoc--experiment-kiwi--release--local--2018-02-08--8.18pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5191fe4b3ca7f865414f4f12fe3b4944f5221568
            message: >-
                JS dist files --
                __adhoc--experiment-kiwi--release--local--2018-02-08--8.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c2125d2171a9d0677e6c3eaf63f346a781132632
            message: >-
                Localized strings --
                __adhoc--experiment-kiwi--release--local--2018-02-08--8.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ba910bcf6bc1840b3e2ab920778af225973ee3f0
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/329e4019b581209ed8a615687e5523808b7d9f1e
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/60e3be0056c1ea4b0e848ff7446b2d6734eba462
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--experiment-kiwi--release--local--2018-02-08--8.18pm
