version: 1.1.9-lumen.2
tag: lumen
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-lumen.2
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-lumen.2
deployedAt: 2018-07-05 11:43 pm UTC  (2018-07-05 4:43 pm Pacific Time)

history:
    adhocBranchName: __adhoc--lumen--current--local--2018-07-05--4.29pm
    commitMessage: __adhoc--lumen--current--local--2018-07-05--4.29pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c56b0b7ec45735a26f9aa8b03eb1cd610589f82b
            message: >-
                JS dist files --
                __adhoc--lumen--current--local--2018-07-05--4.29pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/df37e6afdeedfcbedac32205c8adde6b85d171fa
            message: >-
                Localized strings --
                __adhoc--lumen--current--local--2018-07-05--4.29pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d1322a7c52444fa637df1520a3a54251b0aebdba
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0cf144de7412ca869f61c0b6ec34030b8369f501
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ec6ea921b523885f2610585b3d15e5133d3d2041
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--lumen--current--local--2018-07-05--4.29pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.2/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.2/dist/office.d.ts
    builds using this same tag ("lumen"):
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.js
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/400665195