version: 1.1.5-adhoc.18
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-adhoc.18
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-adhoc.18
deployedAt: 2018-03-29 9:47 pm UTC  (2018-03-29 2:47 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-03-29--2.45pm
    commitMessage: __adhoc--beta--local-enlistment--2018-03-29--2.45pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d9d7524944c2a69be1cc32a2525c3240cd0eabb9
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-03-29--2.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/359aa2d55d2b2434c8edf626be3b8915610e3526
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-03-29--2.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/985a6e8b534192015827554fad11868bdb6bb290
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ca748ab9d5cf87acf915d5446b7824bdd4618077
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6daa2e0fb46c267d9b1cf64e279c6218bc9e992a
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-03-29--2.45pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.18/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.18/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/360052817