version: 1.1.7-adhoc.9
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.7-adhoc.9
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.7-adhoc.9
deployedAt: 2018-05-02 8:51 pm UTC  (2018-05-02 1:51 pm Pacific Time)

history:
    adhocBranchName: __for_merging--beta--16.0.9318.5450--2018-05-02--1.48pm
    commitMessage: __for_merging--beta--16.0.9318.5450--2018-05-02--1.48pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ec41c3b55d00df862e33fab295bab8dee51b92e7
            message: >-
                JS dist files --
                __for_merging--beta--16.0.9318.5450--2018-05-02--1.48pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f1a1b47cd644b60bb0a1937941d7565884684816
            message: >-
                Localized strings --
                __for_merging--beta--16.0.9318.5450--2018-05-02--1.48pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bfeec97bbaa72c8b8873ee5b3399a2dd5813316a
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f21aa21db3f83492aad2ba0cf1df91c9d801a15c
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4ba2bda59fac5e1e48dcbeeb58c260b92789cad6
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __for_merging--beta--16.0.9318.5450--2018-05-02--1.48pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.7-adhoc.9/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.7-adhoc.9/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/374135043