tag: experiment-daedalus
history:
    adhocBranchName: __adhoc--experiment-daedalus--release--local--2018-02-08--4.54pm
    commitMessage: Moved void batch definition back to bottom
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b43b670e0e556c780f5eb2e51bca1eb0099919ac
            message: JS dist files -- Moved void batch definition back to bottom
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9659ab8e5e4ff5de55da0593adbf6201c07600d2
            message: Localized strings -- Moved void batch definition back to bottom
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b6440e561427b30195dacd6f944f8bf254f04064
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f08578dd4b24d9409532b893687513139c2d5592
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d4f97d9135e3a4b10bdfcdaf552c041bbfc8aec6
            message: >-
                [BEGIN PUBLISH UPDATES] -- Moved void batch definition back to
                bottom
