tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-07-17--5.58pm--custom-functions-revamp
    commitMessage: __adhoc--beta--local--2018-07-17--5.58pm--custom-functions-revamp
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ed8d5a6a521dd5681b72242ca0a7bfaddab7cfbf
            message: >-
                JS dist files --
                __adhoc--beta--local--2018-07-17--5.58pm--custom-functions-revamp
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8e2cd1dab9b396ed8212f1a9428b088bd0fd105d
            message: >-
                Localized strings --
                __adhoc--beta--local--2018-07-17--5.58pm--custom-functions-revamp
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3efe06157b68efa6562e87c1b360da73c70b3095
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5a02608f86a6ae87bb420263d68c1ab9f87bbc5b
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8835a098d912a3fb6f8e7e929452e56e80c0665f
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-07-17--5.58pm--custom-functions-revamp
