version: 1.1.7-adhoc.1
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.7-adhoc.1
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.7-adhoc.1
deployedAt: 2018-04-17 10:42 pm UTC  (2018-04-17 3:42 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta-next--16.0.9316.5452--2018-04-17--3.33pm
    commitMessage: __adhoc--beta-next--16.0.9316.5452--2018-04-17--3.33pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e16fedfff2ed83c94edc51501fcd82556bb09eb1
            message: >-
                JS dist files --
                __adhoc--beta-next--16.0.9316.5452--2018-04-17--3.33pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/70dce2bf232ae3917d3d95bc1f33def0a9bb4414
            message: >-
                Localized strings --
                __adhoc--beta-next--16.0.9316.5452--2018-04-17--3.33pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/82e12228e58f4e8769d627359a30bd46c6a9d8c4
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ccd3990d1ac95128a00b06fe8b2e0c7f7566dd58
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0164a69fa8339c4b1ea8c85f5f5804716c31fed4
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta-next--16.0.9316.5452--2018-04-17--3.33pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.7-adhoc.1/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.7-adhoc.1/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/367895554