version: 1.1.9-adhoc.6
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-adhoc.6
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-adhoc.6
deployedAt: 2018-06-26 10:27 am UTC  (2018-06-26 3:27 am Pacific Time)

history:
    adhocBranchName: >-
        __adhoc--release--local-enlistment--2018-06-26--3.11am--16-00-Excel-files-test
    commitMessage: >-
        __adhoc--release--local-enlistment--2018-06-26--3.11am--16-00-Excel-files-test
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/eb35981c7ceba061cdcaf735d8a988bc16c6103f
            message: >-
                JS dist files --
                __adhoc--release--local-enlistment--2018-06-26--3.11am--16-00-Excel-files-test
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c6aaaeab2abbe86f0edacd74c4a93c50fe0eccbf
            message: >-
                Localized strings --
                __adhoc--release--local-enlistment--2018-06-26--3.11am--16-00-Excel-files-test
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a7b9024e9d0514a70aaea7db366bc3e4fdaa5f34
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/15c1747cc61a842fc3de49008acf066504e33571
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ad14071bcc2e603c7e30bac338d3b3e6310726f7
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--local-enlistment--2018-06-26--3.11am--16-00-Excel-files-test


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.6/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.6/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/396816938