tag: adhoc
history:
    adhocBranchName: __adhoc--release-next--16.0.9028.5450--2018-01-30--1.33pm
    commitMessage: __adhoc--release-next--16.0.9028.5450--2018-01-30--1.33pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7753139ee2b73377a3e6dcac964ba9492106d4fd
            message: >-
                JS dist files --
                __adhoc--release-next--16.0.9028.5450--2018-01-30--1.33pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/21c602fddc907172b2ebd6635bb30c2c14ab44a3
            message: >-
                Localized strings --
                __adhoc--release-next--16.0.9028.5450--2018-01-30--1.33pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/955a94048bf36fecb29ee8651259cfbaee61d33b
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/302249dcf7683e81720336adc62d11aa04fcdb76
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3a582713eeaf9009a24cb41033da8169db37335c
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release-next--16.0.9028.5450--2018-01-30--1.33pm
