version: 1.1.9-lumen.3
tag: lumen
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-lumen.3
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-lumen.3
deployedAt: 2018-07-06 5:30 pm UTC  (2018-07-06 10:30 am Pacific Time)

history:
    adhocBranchName: __adhoc--lumen--current--local--2018-07-06--10.26am
    commitMessage: __adhoc--lumen--current--local--2018-07-06--10.26am
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d42e16acfad34030dd2c9b15e37f78cbf53db604
            message: >-
                JS dist files --
                __adhoc--lumen--current--local--2018-07-06--10.26am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6c7274ccadb87d25676f81a45e5f0bb89a198f17
            message: >-
                Localized strings --
                __adhoc--lumen--current--local--2018-07-06--10.26am
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8c01eb4a0a1b0d4840a0d18a1c07c813760771e9
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/13162f257a2b0aa566ff308f87a3cd88a671c411
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/65eca1bfd74ffe66903374ef0fe9781c03d3d18b
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--lumen--current--local--2018-07-06--10.26am


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.3/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.3/dist/office.d.ts
    builds using this same tag ("lumen"):
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.js
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/400983444