tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local--2018-05-25--5.39pm
    commitMessage: __adhoc--beta--local--2018-05-25--5.39pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/41acde7b7c76ff9797b561377afbfbd6e4711f42
            message: JS dist files -- __adhoc--beta--local--2018-05-25--5.39pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8f09feaa22d41bfd2c30e2c0c5af40032cdb5b7e
            message: Localized strings -- __adhoc--beta--local--2018-05-25--5.39pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4e46bec883361ba258307c90d8f300a6c31a4a44
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/17a070b3acd757e6ccefcb8a163090f4605a69dd
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e6c5545f751f86d042674bc4843bc39ce7546c7f
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-05-25--5.39pm
