version: 1.1.9-adhoc.3
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-adhoc.3
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-adhoc.3
deployedAt: 2018-05-18 5:25 am UTC  (2018-05-17 10:25 pm Pacific Time)

history:
    adhocBranchName: >-
        __adhoc--release--local-enlistment--2018-05-17--10.21pm--update-web-files-by-gega
    commitMessage: update web files by gega
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/35e92ba4bcba4146a18dc114dfe61b3c1533d527
            message: JS dist files -- update web files by gega
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/458a27e418e14f7379b89f8707300eee7d693683
            message: Localized strings -- update web files by gega
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/20a5a1a2c656479ab08d1fe799ebf176ac8c6d50
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8b3841a72cb6ab023fdc0df7c3b95b3dcef19f88
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/e44afbc1d91eec1820495b69090e02011fb778c5
            message: '[BEGIN PUBLISH UPDATES] -- update web files by gega'


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.3/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-adhoc.3/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/380539434