version: 1.1.9-lumen.4
tag: lumen
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-lumen.4
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-lumen.4
deployedAt: 2018-07-17 8:29 pm UTC  (2018-07-17 1:29 pm Pacific Time)

history:
    adhocBranchName: __adhoc--lumen--current--local--2018-07-16--10.52pm
    commitMessage: __adhoc--lumen--current--local--2018-07-16--10.52pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f81d3e8ddb5c0cd6ab74237c6810dfd88e2acc53
            message: >-
                JS dist files --
                __adhoc--lumen--current--local--2018-07-16--10.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/151ed52081842fe944a6b4606a62020e88ed0c47
            message: >-
                Localized strings --
                __adhoc--lumen--current--local--2018-07-16--10.52pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bfc53307b8050ea046cb18733126966acd8180c7
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/73fc0ac953927ca75c86ebd965f5a80e113142e2
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0de892dd83dc8b0b23180e2d91d405279927b4c1
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--lumen--current--local--2018-07-16--10.52pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.4/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-lumen.4/dist/office.d.ts
    builds using this same tag ("lumen"):
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.js
        https://unpkg.com/@microsoft/office-js@lumen/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/405076077