tag: experiment-daedalus
history:
    adhocBranchName: __adhoc--experiment-daedalus--release--local--2018-01-25--2.20pm
    commitMessage: Updated strings to remove context.sync references
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b486c5759d1fd77a3b4d4379b2fdf4e67fb11e61
            message: >-
                JS dist files -- Updated strings to remove context.sync
                references
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6e89621e8105a236e0ef4ff9fb40301bc689bf78
            message: >-
                Localized strings -- Updated strings to remove context.sync
                references
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1415d65641e0fc1329608c9700a8bf3147d60109
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/78004b185aa8612ddb0eb1ce4c8e614b1f41e6f3
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c2d50b20652db670050ead77192a4442b9397d95
            message: >-
                [BEGIN PUBLISH UPDATES] -- Updated strings to remove
                context.sync references
