version: 1.1.5-adhoc.5
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-adhoc.5
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-adhoc.5
deployedAt: 2018-02-02 8:30 pm UTC  (2018-02-02 12:30 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--local--2018-02-02--12.26pm--insights-with-pivot-bridge
    commitMessage: __adhoc--beta--local--2018-02-02--12.26pm--insights-with-pivot-bridge
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b42bfdbbd02f8098bce0e659f051639a40d8ce64
            message: >-
                JS dist files --
                __adhoc--beta--local--2018-02-02--12.26pm--insights-with-pivot-bridge
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8b179313253a1e12cae498adcc58c5046541e8d0
            message: >-
                Localized strings --
                __adhoc--beta--local--2018-02-02--12.26pm--insights-with-pivot-bridge
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/45970d26e18e1e00b1cda3739bc00e6d845c8fb6
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/615ecc34efb19ce049ca7d943b9d531da7570ee4
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/fd146a60a81a30aadfa2468cf5082a7f6d75b20a
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local--2018-02-02--12.26pm--insights-with-pivot-bridge


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.5/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.5/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/336719255