tag: custom-functions-preview
history:
    adhocBranchName: >-
        __adhoc--custom-functions-preview--beta--local-enlistment--2018-06-15--5.23pm
    commitMessage: >-
        __adhoc--custom-functions-preview--beta--local-enlistment--2018-06-15--5.23pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/749c97cd0c2664070d0c188d7b672119ee2319f7
            message: >-
                Update office.js loader with "window.CustomFunctionMappings"
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/eab4a1e5abce2039158dc97478fe847e22acceb5
            message: >-
                JS dist files --
                __adhoc--custom-functions-preview--beta--local-enlistment--2018-06-15--5.23pm (excluding "office.js" loader)
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/52f944f89dd5404d15ceea32b55fab18bae826b7
            message: >-
                Localized strings --
                __adhoc--custom-functions-preview--beta--local-enlistment--2018-06-15--5.23pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8de089b8e58ec2ac3743720dd0c70638d75887c0
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/54b31efc00e0375e34cbc69b6a2a721ac0c7ba0e
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2263847ae4e6592dc7101dd77248c63335651fd6
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--custom-functions-preview--beta--local-enlistment--2018-06-15--5.23pm
