tag: experiment-kiwi
history:
    adhocBranchName: __adhoc--experiment-kiwi--release--local--2018-01-24--11.08pm
    commitMessage: __adhoc--experiment-kiwi--release--local--2018-01-24--11.08pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/783599ed72ab6dd168d593b14c611f3f732dc250
            message: >-
                JS dist files --
                __adhoc--experiment-kiwi--release--local--2018-01-24--11.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9775e20509c38032160c0d5d960e751c0c8cfcb7
            message: >-
                Localized strings --
                __adhoc--experiment-kiwi--release--local--2018-01-24--11.08pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/02d3c117ab1afe339f028ce4ee37a5e1720ec122
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2425027915f069dead8528db223bc1a1ab445454
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3f85cb03ff47a1cdd2563456374ff2d140d7fac9
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--experiment-kiwi--release--local--2018-01-24--11.08pm
