tag: experiment-kiwi
history:
    adhocBranchName: __adhoc--experiment-kiwi--release--local--2018-01-24--10.12pm
    commitMessage: __adhoc--experiment-kiwi--release--local--2018-01-24--10.12pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/04525cf10bbcd9303db0d038ccbe54be3ebce34f
            message: >-
                JS dist files --
                __adhoc--experiment-kiwi--release--local--2018-01-24--10.12pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f1e15a5c6a06b7f31ee1a36532c9ae962867d54f
            message: >-
                Localized strings --
                __adhoc--experiment-kiwi--release--local--2018-01-24--10.12pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/245fd3f4ba01147d7098d5f0de1fb55da78089f4
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c51ef424ae8d9bd65cd88c089dcbea2be14fa664
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5423b4d016f6cc8600c5900ce2bd563295af4f60
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--experiment-kiwi--release--local--2018-01-24--10.12pm
