tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-07-25--5.14pm
    commitMessage: __adhoc--beta--local-enlistment--2018-07-25--5.14pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1ccb8eac8ceaf84a5b0d4ad9a8954a7c333df9bb
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-07-25--5.14pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2290cabbeacdbc17b7904a5461e03cc90710eaae
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-07-25--5.14pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2b150ad13f23eac73e74e5864932c3e4ddae9d85
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6a9a2b700dfcbe2d01e3ab775f6df9978fbef083
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/aa263529a40b4f11bf3dcbe300cfb285a42307e2
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-07-25--5.14pm
