tag: adhoc
history:
    adhocBranchName: __adhoc--beta--local-enlistment--2018-03-27--2.18pm
    commitMessage: __adhoc--beta--local-enlistment--2018-03-27--2.18pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/909fbe8ab7cc5fcec6640ac27ce7a07624c13bca
            message: >-
                JS dist files --
                __adhoc--beta--local-enlistment--2018-03-27--2.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4fe2b2f58c5339a1908837acdd9e2b6fcd53db6e
            message: >-
                Localized strings --
                __adhoc--beta--local-enlistment--2018-03-27--2.18pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/94136a5a8edbeb2cbc11a2c95f4f49ea2ad122b4
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/348dfb153cdbfd6008a15c3e868658471e40a3f5
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/321a60ba287c90692e381778e73b587e9cd57f89
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--local-enlistment--2018-03-27--2.18pm
