tag: experiment-kiwi
history:
    adhocBranchName: __adhoc--experiment-kiwi--beta--local--2018-01-18--3.36pm
    commitMessage: added new option to load options
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/02898a46ae1740c6115738412f0cc80338306888
            message: JS dist files -- added new option to load options
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/008d3384da12fdc651777bfb68160d320e2ed830
            message: Localized strings -- added new option to load options
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4c8aa79afcdd1e2db614cc47bacb6ceab6ae061c
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4e6937774ae35807ca5607a3ac65e2577cfad967
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/49a7eebbd2c2467efa8b004daf364dba45a5231b
            message: '[BEGIN PUBLISH UPDATES] -- added new option to load options'
