version: 1.1.3-beta-next.4
tag: beta-next
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.3-beta-next.4
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.3-beta-next.4
deployedAt: 2018-01-19 3:30 am UTC  (2018-01-18 7:30 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta--16.0.9002.5450--2018-01-18--7.20pm--beta-next-9002
    commitMessage: __adhoc--beta--16.0.9002.5450--2018-01-18--7.20pm--beta-next-9002
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b6eab1e753b2b41c3b069f6f1a810f225c1ff3fe
            message: >-
                JS dist files --
                __adhoc--beta--16.0.9002.5450--2018-01-18--7.20pm--beta-next-9002
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d5b97830dfbc19f48923bf1e7ab6ac7053d0ad2d
            message: >-
                Localized strings --
                __adhoc--beta--16.0.9002.5450--2018-01-18--7.20pm--beta-next-9002
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f40520412ad11513ce6f861274a47d92a577f2a6
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/701b2ae19ec9938191905ff264a3cffe515eda00
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/91389a4d42493510631a3735f27893c236b0e7aa
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta--16.0.9002.5450--2018-01-18--7.20pm--beta-next-9002


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.3-beta-next.4/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.3-beta-next.4/dist/office.d.ts
    builds using this same tag ("beta-next"):
        https://unpkg.com/@microsoft/office-js@beta-next/dist/office.js
        https://unpkg.com/@microsoft/office-js@beta-next/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/330653212