tag: adhoc
history:
    adhocBranchName: __adhoc--release--16.0.9112.5451--2018-02-13--2.38pm
    commitMessage: __adhoc--release--16.0.9112.5451--2018-02-13--2.38pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8a9c6a8d31b94a77b0c53467ff7ce6a30c28d61d
            message: >-
                JS dist files --
                __adhoc--release--16.0.9112.5451--2018-02-13--2.38pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/84977a2a938e4db5119c66c332da48be3b722fc6
            message: >-
                Localized strings --
                __adhoc--release--16.0.9112.5451--2018-02-13--2.38pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dce37b5f1913497bfcb7b1ce816062039efdd4d2
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d54e1338bdf2d50eddea6ee2edf9502601171119
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0a508907e6afa2c89ec685d273b755333ef0ef32
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--16.0.9112.5451--2018-02-13--2.38pm
