version: 1.1.5-adhoc.27
tag: adhoc
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-adhoc.27
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-adhoc.27
deployedAt: 2018-04-15 9:03 pm UTC  (2018-04-15 2:03 pm Pacific Time)

history:
    adhocBranchName: __adhoc--release-next--16.0.9315.5450--2018-04-15--1.59pm
    commitMessage: __adhoc--release-next--16.0.9315.5450--2018-04-15--1.59pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/cc67550871b77ea78cb432ffb3ac4533efeaa61f
            message: >-
                JS dist files --
                __adhoc--release-next--16.0.9315.5450--2018-04-15--1.59pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/bd164a34c7daa5133346a9381b48bf31bd4f5347
            message: >-
                Localized strings --
                __adhoc--release-next--16.0.9315.5450--2018-04-15--1.59pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c96b774f20c64700f812fe3be0e520636e05f9ec
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4a68099db9e4e95f4d54db402b9ff676020070af
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/adbe2972fec6df858cc04708043c6e841d70ff57
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release-next--16.0.9315.5450--2018-04-15--1.59pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.27/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-adhoc.27/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/366899603