version: 1.1.9-operational.3
tag: operational
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-operational.3
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-operational.3
deployedAt: 2018-06-01 5:01 pm UTC  (2018-06-01 10:01 am Pacific Time)

history:
    adhocBranchName: __adhoc--operational--current--local--2018-06-01--9.54am--colbys-op
    commitMessage: Updates to experimental apis
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/beb7931e6d4e3c3ae7e0c8b72ad98d79345d9dab
            message: JS dist files -- Updates to experimental apis
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/f7da8b88df3f75f2dbbb6562196ade1eab9230b4
            message: Localized strings -- Updates to experimental apis
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a9f56c5e7a2875ecc3c267ff819f4afe0065128d
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d71b360d0140d8e8258131ce04a6bcd11a0ee771
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/771c5f729c4e95a5d72ca60d3843faa07a380c62
            message: '[BEGIN PUBLISH UPDATES] -- Updates to experimental apis'


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-operational.3/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-operational.3/dist/office.d.ts
    builds using this same tag ("operational"):
        https://unpkg.com/@microsoft/office-js@operational/dist/office.js
        https://unpkg.com/@microsoft/office-js@operational/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/386766253