version: 1.1.7-release-next.1
tag: release-next
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.7-release-next.1
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.7-release-next.1
deployedAt: 2018-05-02 9:41 pm UTC  (2018-05-02 2:41 pm Pacific Time)

history:
    adhocBranchName: __for_merging--release-next--16.0.9330.5450--2018-05-02--1.46pm
    commitMessage: __for_merging--release-next--16.0.9330.5450--2018-05-02--1.46pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3ec2360ce2928c5166daa417e528cb8599d9b640
            message: >-
                JS dist files --
                __for_merging--release-next--16.0.9330.5450--2018-05-02--1.46pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2eda618f1603fce04815f6f5f25b5467a186566e
            message: >-
                Localized strings --
                __for_merging--release-next--16.0.9330.5450--2018-05-02--1.46pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/ee5b05e9b4bf7f3e19110aa278a1ce25b4a99f6c
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/cb58abc9d3faea01bad322a07f1345bd77fe5e5f
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/2016f358e61134142e20ec27171ff4e9624bf8b1
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __for_merging--release-next--16.0.9330.5450--2018-05-02--1.46pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.7-release-next.1/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.7-release-next.1/dist/office.d.ts
    builds using this same tag ("release-next"):
        https://unpkg.com/@microsoft/office-js@release-next/dist/office.js
        https://unpkg.com/@microsoft/office-js@release-next/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/374155893