tag: experiment-daedalus
history:
    adhocBranchName: __adhoc--experiment-daedalus--release--local--2018-01-25--12.05pm
    commitMessage: Added batch pattern with separation of proxy and data.
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/738127dddee3127e45980fdb5f335e761392ff29
            message: >-
                JS dist files -- Added batch pattern with separation of proxy
                and data.
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a7cf6fcd93e1641a5c1de0c1359fecc35be00a9b
            message: >-
                Localized strings -- Added batch pattern with separation of
                proxy and data.
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/c1d547640498ea890d5eb6a61514f260191a79f6
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/8b2a272f1761fd4f4677d80ba9e44ba343a11657
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/5718599de76e491224c273e7d3db5aaa78dc14a0
            message: >-
                [BEGIN PUBLISH UPDATES] -- Added batch pattern with separation
                of proxy and data.
