version: 1.1.5-experiment-daedalus.5
tag: experiment-daedalus
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-experiment-daedalus.5
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-experiment-daedalus.5
deployedAt: 2018-02-08 9:40 pm UTC  (2018-02-08 1:40 pm Pacific Time)

history:
    adhocBranchName: __adhoc--experiment-daedalus--release--local--2018-02-08--1.37pm
    commitMessage: Corrected exported batch function typing
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/deaaf3e72ee971ff4c55295dc0699ad802c1f60c
            message: JS dist files -- Corrected exported batch function typing
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/33e0470a6ff16a58980d740837e99bcf99d761d1
            message: Localized strings -- Corrected exported batch function typing
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1b82642665b200515b8a653742487c97ef3ab2cf
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/0127be36f21fe850ce152704985782958d30b4fc
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/7dda20c2620b14a1fee7dee234f6ee7618f5860f
            message: >-
                [BEGIN PUBLISH UPDATES] -- Corrected exported batch function
                typing


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-experiment-daedalus.5/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-experiment-daedalus.5/dist/office.d.ts
    builds using this same tag ("experiment-daedalus"):
        https://unpkg.com/@microsoft/office-js@experiment-daedalus/dist/office.js
        https://unpkg.com/@microsoft/office-js@experiment-daedalus/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/339191840